### ISSUE TITLE
Add rr support

### ISSUE THREAD

**Issue by bjorn3** [ftilde/ugdb#17]
I really like this gdb interface and I would like to be able to use it with rr too.

**Comment by ftilde** [comment]
I've been meaning to look into rr for quite some time, so this was a 
good reason to finally do so. Adding support was actually quite easy and 
just required changing the spawned gdb process to a rr replay process 
and fiddling with the parameters.

As noted in the commit message, debuggee output in the ugdb tty is not 
possible and requires support from rr. We would need a "--tty" option 
like gdb that controls how stdin/stdout is redirected.

**Comment by bjorn3** [comment]
Thanks! It works great!
