### ISSUE TITLE
Support rd

### ISSUE THREAD

**Issue by lu-zero** [ftilde/ugdb#19]
https://github.com/sidkshatriya/rd is a rust port of rr, would be interested to support it.

**Comment by ftilde** [comment]
On 13.05.2021 08:22, Luca Barbato wrote:
>https://github.com/sidkshatriya/rd is a rust port of rr, would be interested to support it.

That would be nice! I think this aims to be a (more or less) drop-in 
replacement for rr, right? In that case supporting this would just be a 
matter of letting the user choose the rr (or rd!) binary, which could be 
useful anyway.

**Comment by lu-zero** [comment]
That's my understanding at least :)

**Comment by ftilde** [comment]
The rr binary can now be changed using the `rr-path` parameter, for which `rd` can be chosen as well. I've tested it in a small example and it seems to work. Let me know if you find any issues with it!

**Comment by lu-zero** [comment]
Thank you a lot!
