### ISSUE TITLE
Greyed out TUI

### ISSUE THREAD

**Issue by vbarrielle** [ftilde/ugdb#4]
Hi, and thanks for developping this tool, it looks like it can fit my needs better than cgdb.

I was trying it out but I was surprised to see that it didn't render the same on my machine than
in your screenshots:

![ugdb_grey_render](https://user-images.githubusercontent.com/1874105/55630365-c9ed9b00-57b5-11e9-95d5-aabfd7a88098.png)

Nothing preventing me from using ugdb, but that feels weird :)

For information I'm using Konsole on Kubuntu 18.04, but it looks like I have the same behaviour with xterm or alacritty.

**Comment by ftilde** [comment]
Oops, this is actually a problem in `unsegen` where I (for some reason) set the default background color to LightBlack. Of course the default should be to use the "normal" terminal colors for foreground and background. Unfortunately, this requires adding a "Default" variant to the Color enum in unsegen, a breaking change. I will fix this shortly when I collected and fixed some other problems in the API of unsegen and release 0.2.

Up until then a workaround would be to choose another color for LightBlack in your terminal emulator (sorry!).

**Comment by ftilde** [comment]
I've fixed this in unsegen and (for now) patched the unsegen dependency to point at the (unreleased) git version. I will not release an official version until unsegen 0.2 is out (as a crates.io release is not possible with a patched dependency, afaik).

If you build ugdb from git the problem should fixed, though. Feel free to report back if that is not the case!

**Comment by vbarrielle** [comment]
Building from git works, thanks!
