### ISSUE TITLE
Usability of the source and expression windows

### ISSUE THREAD

**Issue by ericonr** [ftilde/ugdb#6]
## Expression window
It could lead a productivity boost if it were possible to write a script that defines what must be in the expression table at startup. This script could be selected via command-line, and would enable returning to a certain function that's being debugged without much hassle.

### Displayed file
Add a shortcut that enables the user to change which file is currently being displayed. That way, you can visually put a breakpoint in that file, and then get back to debugging.
### Watchpoint
Watching a variable is sometimes important as well, and I believe gdb allows for it. So it should be possible to implement a shortcut that allows placing a watchpoint on a certain variable.

**Comment by ftilde** [comment]
### Expression window

Hm, adding expressions to the window via a script would first involve defining some kind of scripting language which (at the moment) I don't see any other use for. What do you think about adding a command line parameter for that? Something like:
```
ugdb --initial-expression="foo.bar" --initial-expression="&baz+37"
```
Then you could instead script the startup of ugdb. If you like that approach: I think this is actually not too difficult to add, so it would be a great first contribution to ugdb.

### Displayed file

Sounds like a useful feature. Should actually not be to difficult to add, as well. (Maybe a little harder than adding the command line option. I'm curios: What does your development environment look like? Do you use some kind of IDE or just an editor? If happen to you vim you could use [vim-ugdb](https://github.com/ftilde/vim-ugdb) to set breakpoints as well.

### Watchpoints

Yes, watchpoints are definitely useful and you can totally use them just like in gdb. It was previously mentioned that it could be useful to add some kind of watchpoint support to the expression table, but I'm not 100% sure how that would look like.

**Comment by ericonr** [comment]
## Expression window
I think you are right, command line options are much better in this case!

## Displayed file
I'm currently an Emacs user, especially because of the emacsclient functionality. Setting this up could depend on using another key combination for navigating between files (or opening a file tree?).

##Watchpoints
I think this functionality could work like a shortcut (some F key) on the expression window. I also thought about something like an alternate breakpoint that you put in lines which declare variables.

**Comment by ftilde** [comment]
Just a thought I had when looking at #15: If you (or anyone else) wants to implement initial expression window values, I think I would prefer now actually prefer your initial suggestion with a script that outputs line separated initial expressions.

**Comment by ftilde** [comment]
Disregarding what I've set before: I've implemented the command line option variant for initial expression window contents now, since that was quite easy.

**Comment by ftilde** [comment]
Watchpoints can now be created for the current expression in the expression table using ctrl-w.

The displayed file can be changed either using the !show <file> command or using the show_file ipc command. Even though a file tree widget would be nice, of course, I probably won't be implementing this myself, since it seems quite a lot of work for a possibly quite niche use case. I would accept contributions, though.

I think this should cover all suggestions you raised in this issue, so I'm going to close it. Of course feel free to report back and/or reopen if you disagree.

**Comment by ftilde** [comment]
One more thing: I've finally taken the time to document the (quite simple) ipc protocol, so developing an ugdb extension for emacs might be an option you or someone else. I personally almost always set breakpoints in ugdb from within vim -- at least when starting out the debugging session at a particular location in the program (which I've quite likely just edited beforehand).
