### ISSUE TITLE
Limit width of source window

### ISSUE THREAD

**Issue by vbarrielle** [ftilde/ugdb#8]
It looks like currently the source window's width is expanded to match the length of the current function name. However, when debugging C++ binaries with highly templated libraries I can have functions with very long names, resulting in the source window taking up the whole width, making it impossible to use the expression and terminal windows.

**Comment by ftilde** [comment]
This should be fixed properly, once configurable layouts (#3) are a thing. Unfortunately I don't have a lot of time to work on this at the moment, so I added a quick fix to master for now.
